version: '3'

services:
  guacamole:
    image: guacamole/guacamole
    ports:
      - 8080:8080
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACAMOLE_HOME=/config
    volumes:
      - ./config/guacamole.properties:/config/guacamole.properties
      - ./config/user-mapping.xml:/config/user-mapping.xml
  guacd:
    image: guacamole/guacd
  desktop:
    build: desktop
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/home/alpine
