version: '3'

services:
  guacamole:
    image: guacamole/guacamole
    ports:
      - 8080:8080
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACAMOLE_HOME=/config
    volumes:
      - ./config:/config
  guacd:
    image: guacamole/guacd
